import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import QueryProvider from "@/providers/tanstack/react-query-privider";
import { ToasterProvider } from "@/providers/toaster/toaster-provider";
import { cookies } from "next/headers";
import { CookieProvider } from "@/providers/cookie-provider";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const cookieStore = await cookies();
    const defaultOpen = cookieStore.get("connect.sid")?.value ? true : false;
    return (
        <CookieProvider defaultOpen={defaultOpen}>
            <QueryProvider>
                <html lang="en">
                    <body
                        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
                    >
                        {children}
                        <ToasterProvider />
                    </body>
                </html>
            </QueryProvider>
        </CookieProvider>
    );
}
